services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: funding-app
        env_file:
            - .env
        ports:
            - "${SERVER_PORT:-8090}:8090"
        volumes:
            - ./data-container:/data
        restart: unless-stopped
