"""Markdown and JSON rendering for quality backlog reports and issues."""
from __future__ import annotations

import datetime
import json

from quality_backlog.models import FindingGroup, SonarMetric
from quality_backlog.triage import labels_for

_MARKER_PREFIX = "quality-backlog-fingerprint:"


def render_report(
    groups: list[FindingGroup],
    selected: list[FindingGroup],
    metrics: list[SonarMetric],
    mode: str,
) -> str:
    today = datetime.date.today().isoformat()
    lines = [
        "# Quality Backlog Report",
        "",
        f"Generated: {today}",
        f"Mode: `{mode}`",
        f"Groups found: {len(groups)}",
        f"Groups selected: {len(selected)}",
        "",
        "## Metrics",
        "",
    ]
    if metrics:
        for metric in sorted(metrics, key=lambda item: item.key):
            lines.append(f"- `{metric.key}`: `{metric.raw_value}`")
    else:
        lines.append("- No project metrics returned by SonarQube.")

    lines.extend(["", "## Selected Groups", ""])
    if not selected:
        lines.append("No actionable groups selected.")
    for index, group in enumerate(selected, start=1):
        lines.extend(
            [
                f"### {index}. {group.component}: {group.theme}",
                "",
                f"- Category: `{group.category}`",
                f"- Priority: `{group.priority}`",
                f"- Rule: `{group.rule}`",
                f"- Findings: `{group.count}`",
                f"- Fingerprint: `{group.fingerprint}`",
                "",
            ],
        )
        for issue in group.issues[:5]:
            line = f":{issue.line}" if issue.line else ""
            lines.append(f"- `{issue.path}{line}` - {issue.message}")
        if group.metric:
            lines.append(f"- Metric `{group.metric.key}` value is `{group.metric.raw_value}`")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_issue_title(group: FindingGroup) -> str:
    title = f"[quality] {group.component}: {group.theme}"
    return title[:77] + "..." if len(title) > 80 else title


def render_issue_body(group: FindingGroup) -> str:
    today = datetime.date.today().isoformat()
    summary = _ai_field(group, "summary", _default_summary(group))
    impact = _ai_field(group, "impact", _default_impact(group))
    recommended_fix = _ai_field(group, "recommendedFix", _default_fix(group))
    examples = _render_examples(group)
    labels = ", ".join(f"`{label}`" for label in labels_for(group))
    return f"""\
## Summary
{summary}

## Priority
`{group.priority}`

## Category
`{group.category}`

## Impact
{impact}

## Evidence
{examples}

## Recommended fix
{recommended_fix}

## Source
- Source: local SonarQube project `crypto`
- Component: `{group.component}`
- Rule/theme: `{group.rule}`
- Findings in group: `{group.count}`
- Labels: {labels}
- Snapshot date: {today}

<!-- {_MARKER_PREFIX} {group.fingerprint} -->

---
Auto-generated by quality backlog triage.
"""


def render_recurrence_comment(group: FindingGroup) -> str:
    today = datetime.date.today().isoformat()
    return (
        f"**Quality backlog recurrence** - {today}\n\n"
        f"Component: `{group.component}`  \n"
        f"Rule/theme: `{group.rule}`  \n"
        f"Findings in latest snapshot: `{group.count}`"
    )


def render_json(groups: list[FindingGroup], selected: list[FindingGroup], mode: str) -> str:
    data = {
        "mode": mode,
        "groupsFound": len(groups),
        "groupsSelected": len(selected),
        "groups": [_group_to_dict(group) for group in groups],
        "selectedFingerprints": [group.fingerprint for group in selected],
    }
    return json.dumps(data, indent=2, sort_keys=True)


def marker_for(fingerprint: str) -> str:
    return f"{_MARKER_PREFIX} {fingerprint}"


def _group_to_dict(group: FindingGroup) -> dict:
    return {
        "fingerprint": group.fingerprint,
        "component": group.component,
        "category": group.category,
        "theme": group.theme,
        "rule": group.rule,
        "priority": group.priority,
        "severity": group.severity,
        "issueType": group.issue_type,
        "count": group.count,
        "metric": None if group.metric is None else {"key": group.metric.key, "value": group.metric.raw_value},
        "issues": [
            {
                "key": issue.key,
                "path": issue.path,
                "line": issue.line,
                "message": issue.message,
                "severity": issue.severity,
                "type": issue.issue_type,
                "url": issue.url,
            }
            for issue in group.issues[:20]
        ],
    }


def _render_examples(group: FindingGroup) -> str:
    if group.metric:
        return f"- Metric `{group.metric.key}` value is `{group.metric.raw_value}`"
    lines = []
    for issue in group.issues[:8]:
        line = f":{issue.line}" if issue.line else ""
        lines.append(f"- `{issue.path}{line}` - {issue.message} ([Sonar]({issue.url}))")
    if len(group.issues) > 8:
        lines.append(f"- ...and {len(group.issues) - 8} more finding(s) in this group.")
    return "\n".join(lines)


def _ai_field(group: FindingGroup, key: str, fallback: str) -> str:
    if group.ai_summary and group.ai_summary.get(key):
        return str(group.ai_summary[key]).strip()
    return fallback


def _default_summary(group: FindingGroup) -> str:
    return f"SonarQube found {group.count} unresolved finding(s) for `{group.theme}` in `{group.component}`."


def _default_impact(group: FindingGroup) -> str:
    if group.category == "security":
        return "This can increase security review risk and should be checked before relying on the affected code."
    if group.category == "bug":
        return "This may hide a runtime defect or incorrect behavior in production paths."
    if group.category == "coverage":
        return "This reduces confidence that future changes will be caught by automated tests."
    return "This increases maintenance cost and makes later changes harder to review safely."


def _default_fix(group: FindingGroup) -> str:
    if group.metric:
        return "Inspect the linked SonarQube metric, add focused tests or refactor the affected code, then rerun Sonar analysis."
    return "Review the listed SonarQube findings, fix the shared rule/theme across the group, and rerun the quality backlog dry-run."

