spring:
    application:
        name: funding-monitor
    config:
        import: optional:classpath:/platform-core.yml
    cloud:
        compatibility-verifier:
            enabled: false

server:
    port: ${MONITOR_SERVER_PORT:8090}

monitor:
    ui:
        version: 2.0.0
