"""Render GitHub issue bodies from analysis results."""
from __future__ import annotations

import datetime


def render_issue_body(result: dict, service: str) -> str:
    """Return a formatted Markdown issue body for *result*.

    Uses today's date (UTC) for the Occurrence section.
    """
    today = datetime.date.today().isoformat()

    summary = result.get("summary", "")
    severity = result.get("severity", "UNKNOWN")
    confidence = float(result.get("confidence", 0.0))
    component = result.get("component", "unknown")
    category = result.get("category", "UNKNOWN")
    impact = result.get("impact", "")
    evidence_items = result.get("evidence", [])
    suspected_cause = result.get("suspectedCause", "")
    recommended_fix = result.get("recommendedFix", "")
    fingerprint = result.get("fingerprint", "")

    evidence_lines = "\n".join(f"- {item}" for item in evidence_items)

    body = f"""\
## Summary
{summary}

## Severity
{severity}

## Confidence
{confidence:.2f}

## Component
{component}

## Category
{category}

## Impact
{impact}

## Evidence
{evidence_lines}

## Suspected cause
{suspected_cause}

## Recommended fix
{recommended_fix}

## Occurrence
Date: {today}
Source: Mac Mini daily Docker log analysis
Container: {service}

## Fingerprint
`{fingerprint}`

<!-- ai-log-fingerprint: {fingerprint} -->

---
*Auto-generated by DeepSeek-V3 daily log analysis*"""

    return body
