#!/usr/bin/env bash
# Scans WARN/ERROR log files from all modules, deduplicates by fingerprint,
# uses DeepSeek API for analysis, and creates GitHub issues for new errors.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/deepseek.sh
source "$SCRIPT_DIR/deepseek.sh"

LOG_BASE="${LOG_BASE_DIR:-/Volumes/DevDisk/dev/projects/crypto/deploy/logs}"
MODULES=("monitor" "engine" "telegram-bot")
SINCE=$(date -v-24H +"%Y-%m-%d %H:%M:%S" 2>/dev/null || date -d "24 hours ago" +"%Y-%m-%d %H:%M:%S")

ensure_labels() {
    gh label create "auto-detected" --color "#e4e669" --description "Auto-detected by error-monitor" --repo "$GITHUB_REPOSITORY" 2>/dev/null || true
}

ensure_labels

found_any=false

for module in "${MODULES[@]}"; do
    logfile="$LOG_BASE/$module/errors.log"
    [ -f "$logfile" ] || { echo "[error-monitor] No log file for $module at $logfile, skipping."; continue; }

    new_lines=$(awk -v since="$SINCE" '$1" "$2 >= since' "$logfile" | grep -E " (ERROR|WARN) " || true)
    [ -z "$new_lines" ] && { echo "[error-monitor] No new WARN/ERROR entries for $module."; continue; }

    found_any=true

    # Unique logger names from new lines
    loggers=$(echo "$new_lines" | grep -oE '(ERROR|WARN) [a-zA-Z0-9._$]+ ' | awk '{print $2}' | sort -u)

    while IFS= read -r logger; do
        [ -z "$logger" ] && continue

        excerpt=$(echo "$new_lines" | grep -F "$logger" | head -30)
        count=$(echo "$new_lines" | grep -cF "$logger" || true)
        fingerprint=$(printf '%s' "$module:$logger" | shasum -a 256 | awk '{print $1}')

        # Skip if open issue already has this fingerprint
        existing=$(gh issue list \
            --label "auto-detected" \
            --state open \
            --json body \
            --jq ".[] | select(.body | contains(\"$fingerprint\")) | .number" \
            --repo "$GITHUB_REPOSITORY" 2>/dev/null || true)
        if [ -n "$existing" ]; then
            echo "[error-monitor] $module/$logger already tracked in issue #$existing, skipping."
            continue
        fi

        severity=$(echo "$excerpt" | grep -oE ' (ERROR|WARN) ' | head -1 | tr -d ' ')
        short_class=$(echo "$logger" | awk -F. '{print $NF}')
        first_ts=$(echo "$excerpt" | head -1 | cut -c1-23)

        echo "[error-monitor] Analyzing $module/$logger ($severity, ${count}x)..."

        system_prompt="You are analyzing error logs for a Java Spring Boot application called funding-arb.
Modules: monitor-app (operator control plane), engine-app (execution runtime), telegram-bot-app."

        user_prompt="Module: $module. Logger: $logger. Severity: $severity. Occurrences in last 24h: $count.

Log excerpt:
$excerpt

In exactly 3 sentences: (1) what triggered this error, (2) likely root cause based on class names and message, (3) one concrete reproduction step.
Be concise and specific. No markdown headers. No bullet points."

        analysis=$(deepseek_chat "$system_prompt" "$user_prompt" 2>/dev/null \
            || echo "Analysis unavailable.")

        gh issue create \
            --repo "$GITHUB_REPOSITORY" \
            --label "bug" \
            --label "auto-detected" \
            --title "[$module] $severity: $short_class" \
            --body "## Summary
**Module:** \`$module\` | **Severity:** \`$severity\` | **Logger:** \`$logger\`
**First seen (last 24h):** $first_ts | **Occurrences:** $count
**Fingerprint:** \`$fingerprint\`

## Log Excerpt
\`\`\`
$excerpt
\`\`\`

## Analysis
$analysis

---
*Auto-generated by error-monitor — $(date -u +%Y-%m-%dT%H:%M:%SZ)*"

        echo "[error-monitor] Created issue for $module/$logger."
    done <<< "$loggers"
done

if [ "$found_any" = false ]; then
    echo "[error-monitor] No log files found. Ensure Docker volumes are mounted and services have run."
fi
