package com.crypto.funding.domain.trade;

public enum TradeJournalEventCode
{
    CANDIDATE_APPROVED,
    CANDIDATE_REJECTED,
    CANDIDATE_DELETED,
    FUNDING_EVENT_CREATED,
    FUNDING_EVENT_ARMED,
    ARMED_TRADE_CREATED,
    ARMED_TRADE_UPDATED,
    ARMED_TRADE_CANCELLED
}
